# Generated by Django 3.0.4 on 2020-03-08 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200307_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delivered_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 1, 19, 7, 496449)),
        ),
    ]
